### PR TITLE
typo + media query overlap fix

### PR DESCRIPTION
**Pull request by erutan**
Wrong decimal point for smaller sixth images, that was a simple fix.

I also created a new breakpoint - not a huge deal but before you'd have two different media queries competing at 380px.

### CODE REVIEW

**Comment by erutan** [comment]
The second commit changes the media query by 4 pixels to ensure that the iPhone 6 isn't being sent overly large assets. Not life changing, but it will be a popular model (makes sense to target), and unless this negatively impacts android phones that have/will have a larger market share does more good than harm.

**Comment by stopfstedt** [comment]
Looks good to me. @erykmynn , any second opinion on this before I merge it?

**Comment by erykmynn** [comment]
4 pixels should be fine.  Is that a picture module breakpoint or the CSS?

The "Breakpoints" media queries are only written on the Picture markup, not
elsewhere--so it doesn't matter if two are slightly different or the css is
different.  If it was a CSS media query, I am not sure the result will be
as desired, as those don't affect the served images.

If we find that the images at the affected size are a few pixels shy of
their container, we may want to fix that, but we left some fudge factor in
all the sizes so it should be fine.

-Eric

On Mon, Sep 15, 2014 at 10:19 AM, Stefan Topfstedt <notifications@github.com

**Comment by erutan** [comment]
SCSS.  I should edit the matching breakpoint module breakpoint as well so it actually works as intended, though the first commit was the more meaningful one.

At this point just pull in the first commit?

**Comment by erykmynn** [comment]
yes, I believe so -- that is in the feature.  it will require a FR on
deploy and probably should be tested

-Eric

**Comment by erutan** [comment]
I just reverted the last commit - will be able to just pull in the typo and fixed the two media queries applying at the same breakpoint issue without worrying about the best way to deal with iPhone 6 assets.

**Comment by stopfstedt** [comment]
reviewed and merged. thanks @erutan !

**Pull request merged**
